[package]
name = "toge-slint"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
toge-core.workspace = true
slint = { version = "=1.17.1", default-features = false, features = ["std", "backend-winit", "renderer-software", "compat-1-2"] }
time = { version = "0.3", features = ["formatting"] }
clipboard-rs = { version = "0.3.5", default-features = false, features = ["wayland"] }

[build-dependencies]
slint-build = "=1.17.1"

[dev-dependencies]
tempfile = "3"
